package _2.`4`

fun exceptionExample() {
    throw Exception("Exception occurred!")
}

fun main() {
    exceptionExample()
}
